# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

# More info about west manifests: https://docs.zephyrproject.org/latest/develop/west/manifest.html
manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      # revision: v3.3.0
      revision: v3.4.0
      import:
        # That puts all the zephyr dependencies in ../zephyr-external
        path-prefix: zephyr-external
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_stm32  # required by the nucleo boards (STM32 based)
          - mbedtls
          # TODO: It would be better to have zenoh-pico here
